-- OASIS Supabase schema
-- Run this in the Supabase SQL editor before deploying to Vercel.

create table if not exists public.oasis_joy_entries (
  id bigint generated by default as identity primary key,
  lang text not null check (lang in ('en', 'zh', 'tc')),
  text text not null check (char_length(text) between 3 and 220),
  created_at timestamptz not null default now()
);

create index if not exists oasis_joy_entries_lang_created_at_idx
  on public.oasis_joy_entries (lang, created_at desc);

create unique index if not exists oasis_joy_entries_lang_text_idx
  on public.oasis_joy_entries (lang, text);

alter table public.oasis_joy_entries enable row level security;

drop policy if exists "OASIS joy public read" on public.oasis_joy_entries;
create policy "OASIS joy public read"
  on public.oasis_joy_entries
  for select
  using (true);

drop policy if exists "OASIS joy public insert" on public.oasis_joy_entries;
create policy "OASIS joy public insert"
  on public.oasis_joy_entries
  for insert
  with check (
    lang in ('en', 'zh', 'tc')
    and char_length(text) between 3 and 220
  );

create table if not exists public.oasis_audio_assets (
  sound_key text primary key check (sound_key in ('fire', 'cat', 'rain', 'leaves')),
  label text not null,
  bucket text not null default 'oasis-audio',
  object_path text not null,
  mime_type text not null default 'audio/wav',
  source_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.oasis_audio_assets enable row level security;

drop policy if exists "OASIS audio metadata public read" on public.oasis_audio_assets;
create policy "OASIS audio metadata public read"
  on public.oasis_audio_assets
  for select
  using (true);

create table if not exists public.oasis_pageviews (
  id bigint generated by default as identity primary key,
  lang text check (lang in ('en', 'zh', 'tc')),
  route text,
  path text not null,
  referrer text,
  user_agent text,
  device_type text,
  country text,
  created_at timestamptz not null default now()
);

create index if not exists oasis_pageviews_created_at_idx
  on public.oasis_pageviews (created_at desc);

create index if not exists oasis_pageviews_route_created_at_idx
  on public.oasis_pageviews (route, created_at desc);

alter table public.oasis_pageviews enable row level security;

drop policy if exists "OASIS pageviews public insert" on public.oasis_pageviews;
create policy "OASIS pageviews public insert"
  on public.oasis_pageviews
  for insert
  with check (true);

insert into public.oasis_joy_entries (lang, text)
values
  ('en', 'A stranger held the elevator and smiled like they had all the time in the world.'),
  ('en', 'The first sip of tea was exactly the right temperature.'),
  ('en', 'A patch of sunlight landed on my notebook and stayed there.'),
  ('zh', '今天路过一家面包店，刚好闻到热面包出炉的味道。'),
  ('zh', '有人很认真地听我把一句话说完。'),
  ('zh', '午后的光落在杯子边缘，看起来像一个小小的奖励。'),
  ('tc', '今天路過一家麵包店，剛好聞到熱麵包出爐的味道。'),
  ('tc', '有人很認真地聽我把一句話說完。'),
  ('tc', '午後的光落在杯子邊緣，看起來像一個小小的獎勵。')
on conflict do nothing;

insert into public.oasis_audio_assets (sound_key, label, bucket, object_path, mime_type, source_url)
values
  ('fire', 'Woodfire', 'oasis-audio', 'fire.wav', 'audio/wav', 'https://assets.mixkit.co/active_storage/sfx/2432/2432-84.wav'),
  ('cat', 'Cat Purr', 'oasis-audio', 'cat.wav', 'audio/wav', 'https://upload.wikimedia.org/wikipedia/commons/6/6e/Cat_purring_panting.ogg'),
  ('rain', 'Soft Rain', 'oasis-audio', 'rain.wav', 'audio/wav', 'https://assets.mixkit.co/active_storage/sfx/2448/2448-84.wav'),
  ('leaves', 'Autumn Leaves', 'oasis-audio', 'leaves.wav', 'audio/wav', 'https://assets.mixkit.co/active_storage/sfx/1204/1204-84.wav')
on conflict (sound_key) do update set
  label = excluded.label,
  bucket = excluded.bucket,
  object_path = excluded.object_path,
  mime_type = excluded.mime_type,
  source_url = excluded.source_url,
  updated_at = now();

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('oasis-audio', 'oasis-audio', true, 10485760, array['audio/wav', 'audio/mpeg', 'audio/ogg'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "OASIS audio public read" on storage.objects;
create policy "OASIS audio public read"
  on storage.objects
  for select
  using (bucket_id = 'oasis-audio');
